version: 2

jobs:
  build:
    working_directory: /ccwang
    docker:
      - image: bennywang/node
    steps:
      - checkout

      - run:
          name: Install Node.js dependencies
          command: yarn install

      # - run:
      #     name: Lint Test
      #     command: yarn run test:lint

      - run:
          name: Unit Test
          command: yarn test:unit

      - run:
          name: Build
          command: yarn build

      - run:
          name: Deploy to production
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync public/ s3://app.ccwang.com --delete
            fi
